### ISSUE TITLE
Update input value based on arrow position

### ISSUE THREAD

**Issue by ovlb** [ovlb/vue-a11y-combobox#5]
Current: The input value is the string the user typed, even if they navigate the suggestions with the keyboard.

WAI-ARIA authoring practices state that «the character string the user has typed will become the value of the textbox unless the user selects a value in the popup.» 

### To-Do

- [ ] Store user input outside `v-model`
- [ ] Update input value on `@keyup.down` and `@keyup.up`
- [ ] `$emit` current value on `@keyup.enter`
- [ ] Reset input value to the typed string if the arrow navigation reaches the end/beginning of the list
