### ISSUE TITLE
Expose CSS classes to allow styling  

### ISSUE THREAD

**Issue by ovlb** [ovlb/vue-a11y-combobox#6]
Currently classes are only added to the components if the `isStyled` prop is set to `true`.

To allow easier styling for implementation the components should always provide classes and apply default styling through an additional class (e.g. `--has-default` modifier).
Additionally expose CSS custom properties to allow overwriting colors and spacing.

### To-Do

- [ ] Always expose BEM classes
- [ ] Add default styling if `isStyled` is passed as `true`
- [ ] Add CSS custom properties for colors and spacing
